### ISSUE TITLE
problem with :// chars

### ISSUE THREAD

**Issue by M0TRIX** [alexruperez/ARDeepLinkButton#1]
cheek this scenario :

i have a payment page designed by angular langue web side

user click on a payment button any i redirect it to the payment web page then after been successful or unsuccessful payment it should return to app by clicking on “return to app” button on web site i tried to implement this by universal link like this way : iosuser:// but wont open this link because of special chars in url. then i tried app site association method which i faced cann’t parse app site association file

do you have any solution  for this ?

is this library solves this problem

**Comment by alexruperez** [comment]
`iosuser://` is not universal linking, it's just an [url scheme](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/communicating_with_other_apps_using_custom_urls).

To use [universal linking](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) you will need the apple-app-site-association well configured. You can use for example [Branch Apple App Site Association Validator](https://branch.io/resources/aasa-validator/) to validate your configuration.

This library only helps when you have another app that you want your user to download from another app.
